/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /** Health */
    get: operations["health_health_get"];
  };
  "/api/v1/projects": {
    /** List Projects */
    get: operations["list_projects_api_v1_projects_get"];
    /** Create Project */
    post: operations["create_project_api_v1_projects_post"];
  };
  "/api/v1/projects/{project_id}": {
    /** Get Project */
    get: operations["get_project_api_v1_projects__project_id__get"];
    /** Delete Project */
    delete: operations["delete_project_api_v1_projects__project_id__delete"];
  };
  "/api/v1/blueprints/project/{project_id}": {
    /** Get Blueprint By Project */
    get: operations["get_blueprint_by_project_api_v1_blueprints_project__project_id__get"];
  };
  "/api/v1/exports": {
    /** Create Export */
    post: operations["create_export_api_v1_exports_post"];
  };
  "/api/v1/exports/{export_id}": {
    /** Get Export */
    get: operations["get_export_api_v1_exports__export_id__get"];
  };
  "/api/v1/exports/project/{project_id}": {
    /** List Project Exports */
    get: operations["list_project_exports_api_v1_exports_project__project_id__get"];
  };
  "/api/v1/shares": {
    /** Create Share */
    post: operations["create_share_api_v1_shares_post"];
  };
  "/api/v1/shares/project/{project_id}": {
    /** List Project Shares */
    get: operations["list_project_shares_api_v1_shares_project__project_id__get"];
  };
  "/api/v1/shares/{share_id}": {
    /** Revoke Share */
    delete: operations["revoke_share_api_v1_shares__share_id__delete"];
  };
  "/api/v1/public/share/{token}": {
    /** Get Public Share */
    get: operations["get_public_share_api_v1_public_share__token__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** APIDesign */
    APIDesign: {
      /**
       * Style
       * @default REST
       */
      style?: string;
      /**
       * Base Url
       * @default /api/v1
       */
      base_url?: string;
      /** Endpoints */
      endpoints?: components["schemas"]["APIEndpoint"][];
      /**
       * Versioning
       * @default
       */
      versioning?: string;
    };
    /** APIEndpoint */
    APIEndpoint: {
      /** Method */
      method: string;
      /** Path */
      path: string;
      /**
       * Description
       * @default
       */
      description?: string;
      /**
       * Auth Required
       * @default true
       */
      auth_required?: boolean;
    };
    /** Architecture */
    Architecture: {
      /**
       * Pattern
       * @default
       */
      pattern?: string;
      /** Layers */
      layers?: string[];
      /**
       * Diagram
       * @default
       */
      diagram?: string;
      /**
       * Description
       * @default
       */
      description?: string;
    };
    /** Blueprint */
    Blueprint: {
      /** Id */
      id: string;
      /** Project Id */
      project_id: string;
      /** User Id */
      user_id: string;
      /** Original Idea */
      original_idea: string;
      sections: components["schemas"]["BlueprintSections"];
      /**
       * Version
       * @default 1.1
       */
      version?: string;
      /**
       * Created At
       * @default
       */
      created_at?: string;
      /**
       * Updated At
       * @default
       */
      updated_at?: string;
    };
    /**
     * BlueprintSections
     * @description All 9 sections of the engineering blueprint.
     */
    BlueprintSections: {
      idea_clarification?: components["schemas"]["IdeaClarification"] | null;
      tech_stack?: components["schemas"]["TechStack"] | null;
      architecture?: components["schemas"]["Architecture"] | null;
      database_schema?: components["schemas"]["DatabaseSchema"] | null;
      api_design?: components["schemas"]["APIDesign"] | null;
      implementation_roadmap?: components["schemas"]["ImplementationRoadmap"] | null;
      security_deployment?: components["schemas"]["SecurityDeployment"] | null;
      testing_strategy?: components["schemas"]["TestingStrategy"] | null;
      documentation?: components["schemas"]["Documentation"] | null;
    };
    /** DBTable */
    DBTable: {
      /** Name */
      name: string;
      /** Columns */
      columns?: string[];
      /**
       * Description
       * @default
       */
      description?: string;
    };
    /** DatabaseSchema */
    DatabaseSchema: {
      /** Tables */
      tables?: components["schemas"]["DBTable"][];
      /** Relationships */
      relationships?: string[];
    };
    /** Documentation */
    Documentation: {
      /**
       * Api Docs
       * @default
       */
      api_docs?: string;
      /**
       * Readme
       * @default
       */
      readme?: string;
      /**
       * Adr
       * @default
       */
      adr?: string;
      /** Notes */
      notes?: string[];
    };
    /** Export */
    Export: {
      /** Id */
      id: string;
      /** Project Id */
      project_id: string;
      /** User Id */
      user_id: string;
      format: components["schemas"]["ExportFormat"];
      /** @default pending */
      status?: components["schemas"]["ExportStatus"];
      /** File Url */
      file_url?: string | null;
      /** Error Message */
      error_message?: string | null;
      /**
       * Created At
       * @default
       */
      created_at?: string;
      /** Completed At */
      completed_at?: string | null;
    };
    /** ExportCreate */
    ExportCreate: {
      /** Project Id */
      project_id: string;
      format: components["schemas"]["ExportFormat"];
    };
    /**
     * ExportFormat
     * @enum {string}
     */
    ExportFormat: "markdown" | "pdf" | "json";
    /** ExportResponse */
    ExportResponse: {
      /** Export Id */
      export_id: string;
      status: components["schemas"]["ExportStatus"];
      /** File Url */
      file_url?: string | null;
      /**
       * Message
       * @default
       */
      message?: string;
    };
    /**
     * ExportStatus
     * @enum {string}
     */
    ExportStatus: "pending" | "processing" | "completed" | "failed";
    /**
     * GenerationStatus
     * @enum {string}
     */
    GenerationStatus: "pending" | "running" | "completed" | "failed";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** IdeaClarification */
    IdeaClarification: {
      /** Title */
      title: string;
      /** Summary */
      summary: string;
      /** Key Features */
      key_features?: string[];
      /**
       * Target Users
       * @default
       */
      target_users?: string;
      /** Success Metrics */
      success_metrics?: string[];
    };
    /** ImplementationRoadmap */
    ImplementationRoadmap: {
      /** Phases */
      phases?: components["schemas"]["RoadmapPhase"][];
      /**
       * Total Duration
       * @default
       */
      total_duration?: string;
    };
    /** Project */
    Project: {
      /** Id */
      id: string;
      /** User Id */
      user_id: string;
      /** Name */
      name: string;
      /** Original Idea */
      original_idea: string;
      /** @default pending */
      status?: components["schemas"]["GenerationStatus"];
      /**
       * Current Stage
       * @default 0
       */
      current_stage?: number;
      /**
       * Total Stages
       * @default 7
       */
      total_stages?: number;
      /** Blueprint Id */
      blueprint_id?: string | null;
      /** Error Message */
      error_message?: string | null;
      /**
       * Created At
       * @default
       */
      created_at?: string;
      /**
       * Updated At
       * @default
       */
      updated_at?: string;
    };
    /** ProjectCreate */
    ProjectCreate: {
      /** Name */
      name: string;
      /** Original Idea */
      original_idea: string;
    };
    /** ProjectShare */
    ProjectShare: {
      /** Id */
      id: string;
      /** Project Id */
      project_id: string;
      /** User Id */
      user_id: string;
      /** Share Token */
      share_token: string;
      /** @default public */
      visibility?: components["schemas"]["ShareVisibility"];
      /**
       * View Count
       * @default 0
       */
      view_count?: number;
      /** Expires At */
      expires_at?: string | null;
      /**
       * Created At
       * @default
       */
      created_at?: string;
    };
    /** ProjectSummary */
    ProjectSummary: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      status: components["schemas"]["GenerationStatus"];
      /** Current Stage */
      current_stage: number;
      /** Total Stages */
      total_stages: number;
      /** Created At */
      created_at: string;
      /**
       * Has Blueprint
       * @default false
       */
      has_blueprint?: boolean;
    };
    /** PublicBlueprintResponse */
    PublicBlueprintResponse: {
      /** Project Name */
      project_name: string;
      /** Original Idea */
      original_idea: string;
      sections: components["schemas"]["BlueprintSections"];
      /** Created At */
      created_at: string;
      /** Share Token */
      share_token: string;
    };
    /** RoadmapPhase */
    RoadmapPhase: {
      /** Phase */
      phase: number;
      /** Title */
      title: string;
      /**
       * Duration
       * @default
       */
      duration?: string;
      /** Tasks */
      tasks?: string[];
    };
    /** SecurityDeployment */
    SecurityDeployment: {
      /**
       * Auth
       * @default
       */
      auth?: string;
      /**
       * Https
       * @default true
       */
      https?: boolean;
      /**
       * Environment
       * @default
       */
      environment?: string;
      /**
       * Monitoring
       * @default
       */
      monitoring?: string;
      /** Notes */
      notes?: string[];
    };
    /** ShareCreate */
    ShareCreate: {
      /** Project Id */
      project_id: string;
      /** @default public */
      visibility?: components["schemas"]["ShareVisibility"];
      /** Expires In Days */
      expires_in_days?: number | null;
    };
    /** ShareResponse */
    ShareResponse: {
      /** Share Id */
      share_id: string;
      /** Share Token */
      share_token: string;
      /** Share Url */
      share_url: string;
      visibility: components["schemas"]["ShareVisibility"];
      /** Expires At */
      expires_at?: string | null;
    };
    /**
     * ShareVisibility
     * @enum {string}
     */
    ShareVisibility: "public" | "private";
    /** TechStack */
    TechStack: {
      /** Frontend */
      frontend?: {
        [key: string]: string;
      };
      /** Backend */
      backend?: {
        [key: string]: string;
      };
      /** Database */
      database?: {
        [key: string]: string;
      };
      /** Infrastructure */
      infrastructure?: {
        [key: string]: string;
      };
    };
    /** TestingStrategy */
    TestingStrategy: {
      /**
       * Unit
       * @default
       */
      unit?: string;
      /**
       * Integration
       * @default
       */
      integration?: string;
      /**
       * E2E
       * @default
       */
      e2e?: string;
      /**
       * Coverage Target
       * @default 80%
       */
      coverage_target?: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Health */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** List Projects */
  list_projects_api_v1_projects_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectSummary"][];
        };
      };
    };
  };
  /** Create Project */
  create_project_api_v1_projects_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Project */
  get_project_api_v1_projects__project_id__get: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Project */
  delete_project_api_v1_projects__project_id__delete: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Blueprint By Project */
  get_blueprint_by_project_api_v1_blueprints_project__project_id__get: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Blueprint"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Export */
  create_export_api_v1_exports_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExportCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        content: {
          "application/json": components["schemas"]["ExportResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Export */
  get_export_api_v1_exports__export_id__get: {
    parameters: {
      path: {
        export_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Export"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Project Exports */
  list_project_exports_api_v1_exports_project__project_id__get: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Export"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Share */
  create_share_api_v1_shares_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShareCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ShareResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Project Shares */
  list_project_shares_api_v1_shares_project__project_id__get: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectShare"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Revoke Share */
  revoke_share_api_v1_shares__share_id__delete: {
    parameters: {
      path: {
        share_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Public Share */
  get_public_share_api_v1_public_share__token__get: {
    parameters: {
      path: {
        token: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PublicBlueprintResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
